# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Tim Puphal
name: Tim Puphal
position: Research Scientist
email: timpuphal@gmail.com
description: |
  I am a researcher in motion planning for mobile robots. I am an associate at Honda Research Institute [Japan](https://www.jp.honda-ri.com/en/) and [Europe](https://www.honda-ri.de/) 
  where we are pushing the intelligence and cooperative interaction of robots in human environments.
  I received my Ph.D from the [Technical University of Darmstadt](https://www.tu-darmstadt.de/index.en.jsp) in 2021 where I was advised by
  [Julian Eggert](https://scholar.google.co.jp/citations?user=pwrMce4AAAAJ&hl=ja) and
  [Jürgen Adamy](https://scholar.google.com/citations?user=cP84NS8AAAAJ&hl=en).

  My current research interests are primarily in robust planning, cooperative planning and human-robot interaction.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://timpuphal.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: timpuphal
github_username: timpuphal
google_scholar: 7e8eFrIAAAAJ&hl
google_patents: ?q=(tim+puphal)&oq=tim+puphal

# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  style: compact

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
